apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-bench-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/NanaGyamfiPrempeh30/eks-karpenter-gitops-bench.git
    targetRevision: main
    path: gitops/apps/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: gitops-bench-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
